### ISSUE TITLE
Should Langohr docs warn against sharing channels between threads?

### ISSUE THREAD

**Issue by eigenhombre** [michaelklishin/langohr#73]
In https://www.rabbitmq.com/api-guide.html the docs state clearly that channel instances shouldn't be shared across threads.  We recently experienced a deadlock that looks likely to be caused by failure to abide by this.  Should a warning about this be included in the Langohr docs somewhere since these may be a significant source of understanding of RMQ semantics for many people (as they were for us)?  The supplied examples in the Langohr docs actually violate this recommendation / requirement as well (see http://clojurerabbitmq.info/articles/getting_started.html).

**Comment by michaelklishin** [comment]
What examples violate this? I couldn't find any in the Getting Started guide.

Everything that's true for the Java client applies to Langohr. Sharing channels between threads is a bad idea when publishing, although even that is not always true: publishing from a consumer callback is safe because consumer work service in the Java client dispatches consume methods with a per-channel ordering guarantee.

I welcome specific documentation improvements. Java, .NET and Ruby (Bunny) clients have decent concurrency considerations sections in their docs.

**Comment by eigenhombre** [comment]
@michaelklishin thanks for your reply.  I could be missing something, but doesn't `blabbr` in *One to Many Pubsub* share channels between the consumers?  `weathr` does the same.  Admittedly these are on the consumer side, but the aforementioned RMQ warning does not distinguish between producers and consumers: "While some operations on channels are safe to invoke concurrently, some are not and will result in incorrect frame interleaving on the wire."  At the very least, if consumers can safely share channels but producers not, would it make sense to at least mention this in the docs?  The Bunny docs do seem clearer ("Concurrency Considerations").  Thanks again.
CC @loganmhb

**Comment by michaelklishin** [comment]
@eigenhombre feel free to submit a PR for Langohr docs.

**Comment by michaelklishin** [comment]
Those examples share a channel for consuming. There is no concurrency besides what the client does internally to make delivery dispatch concurrent. I've explained above why that is safe.
