### ISSUE TITLE
Seemingly no heartbeat

### ISSUE THREAD

**Issue by shmish111** [michaelklishin/langohr#82]
I am setting up a connection to Rabbit using

`(rmq/connect (assoc (:rabbit conf) :requested-heartbeat 3))`

I have 3 subscribers to 3 channels, no producers. When I shutdown the rabbit server, nothing happens to my client. I would expect it to report missing heartbeat after 1.5 seconds and close the connection after 3 seconds. I have left the program running with rabbit down for quite a few minutes and nothing.

I'm using langohr 3.5.1

I have checked `.getHeartbeat rabbit-conn` and it is correctly set to 3. I have also tried setting `:connection-timeout 5` which I believe is 5ms. If I set that to 1 then my app fails to start up (timeout too small to make the initial connection), so I'm sure that setting is correct as well.

**Comment by michaelklishin** [comment]
Missing heartbeats will be reported together with connection closure. The fact that you shut down RabbitMQ likely means its TCP socket has a chance to notify the one used by the Java client and it starts a shutdown sequence + disables heartbeat monitor because it already knows the peer is down. Then recovery could kick in depending on settings.

I cannot reproduce. Please post questions to the mailing list in the future.
